## 2.1. 数据操作

使用 arange 创建一个行向量 x。这个行向量包含以0开始的前12个整数，它们默认创建为整数。也可指定创建类型为浮点数。张量中的每个值都称为张量的 元素（element）。

In [19]:
import torch# 首先，我们导入torch。请注意，虽然它被称为PyTorch，但是代码中使用torch而不是pytorch。

x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

可以通过张量的shape属性来访问张量（沿每个轴的长度）的形状 。

In [20]:
x.shape

torch.Size([12])

In [21]:
x.numel()

12

In [22]:
r = x.reshape(3,4)
e = x.reshape(-1,6)
r,e

(tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]),
 tensor([[ 0,  1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10, 11]]))

格式为CHW，即通道数、高度、宽度


In [23]:
torch.zeros((2,3,4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [24]:
torch.ones((2,3,2))

tensor([[[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]]])

PyTorch 的默认张量类型就是浮点数，具体来说是 32位单精度浮点数


In [ ]:
torch.randn(3,4)#生成一个3行4列的张量，元素服从标准正态分布

tensor([[ 1.2778,  0.0950, -0.1447, -0.2830],
        [ 1.5437,  0.4544,  0.6793, -1.9134],
        [-1.6786, -1.8169,  1.0985,  0.7784]])

对于任意具有相同形状的张量， 常见的标准算术运算符（+、-、*、/和**）都可以被升级为按元素运算。 我们可以在同一形状的任意两个张量上调用按元素操作。 在下面的例子中，我们使用逗号来表示一个具有5个元素的元组，其中每个元素都是按元素操作的结果。

In [26]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
print(x.shape, y.shape)
print("--------------------------------------------------------------")
x + y, x - y, x * y, x / y, x ** y  # **运算符是求幂运算
torch.exp(x)

torch.Size([4]) torch.Size([4])
--------------------------------------------------------------


tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

torch.cat((X, Y), dim=...) 是 PyTorch 中的**张量拼接（Concatenate）**命令。它用于将两个张量 X 和 Y 沿着指定的维度（轴）连接在一起，形成一个新的更大的张量。

参数 dim 决定了沿着哪个维度进行拼接：

    dim=0：沿着第 0 个维度（即行）拼接。可以理解为垂直方向的拼接，把张量上下堆叠起来。这要求 X 和 Y 在其他维度（如列数）上的形状必须完全一致。
    dim=1：沿着第 1 个维度（即列）拼接。可以理解为水平方向的拼接，把张量左右并排拼起来。这要求 X 和 Y 在其他维度（如行数）上的形状必须完全一致。

In [27]:
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

有时，我们想通过逻辑运算符构建二元张量。 以X == Y为例： 对于每个位置，如果X和Y在该位置相等，则新张量中相应项的值为1。 这意味着逻辑语句X == Y在该位置处为真，否则该位置为0。

In [28]:
X > Y

tensor([[False, False, False, False],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]])

对张量中的所有元素进行求和，会产生一个单元素张量。

In [29]:
X.sum()

tensor(66.)

### 2.1.3.广播机制
我们看到了如何在相同形状的两个张量上执行按元素操作。 在某些情况下，即使形状不同，我们仍然可以通过调用 广播机制（broadcasting mechanism）来执行按元素操作。 这种机制的工作方式如下：

1. 通过适当复制元素来扩展一个或两个数组，以便在转换之后，两个张量具有相同的形状；

2. 对生成的数组执行按元素操作。

In [30]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

由于a和b分别是(3, 1)
和(1, 2)
矩阵，如果让它们相加，它们的形状不匹配。 我们将两个矩阵广播为一个更大的(3,2)
矩阵，如下所示：**矩阵a将复制列， 矩阵b将复制行，然后再按元素相加。**

In [31]:
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

### 2.1.4.索引和切片

就像在任何其他Python数组中一样，张量中的元素可以通过索引访问。 与任何Python数组一样：第一个元素的索引是0，最后一个元素索引是-1； 可以指定范围以包含第一个元素和最后一个之前的元素。

注意：在 PyTorch 的索引规则中，当你对多维张量只使用一个索引时，**这个索引默认作用在第 0 维（即最外层维度）上。**

In [32]:
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
print(X)
X[-1], X[1:3]#切片操作是：是左闭右开区间

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])


(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

除读取外，我们还可以通过指定索引来将元素写入矩阵。

In [33]:
X[1, 2] = 9#索引操作是使用","来进行的
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

如果我们想为多个元素赋值相同的值，我们只需要索引所有元素，然后为它们赋值。 例如，[0:2, :]访问第1行和第2行，其中“:”代表沿轴1（列）的所有元素。 虽然我们讨论的是矩阵的索引，但这也适用于向量和超过2个维度的张量。

In [34]:
X[0:1, :] = 8
X[2,0] = 6
X

tensor([[ 8.,  8.,  8.,  8.],
        [ 4.,  5.,  9.,  7.],
        [ 6.,  9., 10., 11.]])

### 2.1.6 转换为其他Python对象

将深度学习框架定义的张量转换为NumPy张量（ndarray）很容易，反之也同样容易。 
- Numpy数组转换为Torch张量：默认情况下，当您使用 torch.from_numpy() 或 torch.tensor() 将Numpy数组转换为Torch张量时，它们在内存中是独立的，不再共享内存。对其中一方的修改不会影响另一方。

- Torch张量转换为Numpy数组：当您使用 .numpy() 方法将Torch张量转换为Numpy数组时，它们是共享底层内存的。这意味着对张量的修改会直接反映在对应的Numpy数组上，反之亦然。

In [35]:
A = X.numpy()#PyTorch 的张量转换为 NumPy 数组
B = torch.tensor(A)#将 NumPy 数组（或其他类似数组的 Python 数据结构）转换为 PyTorch 张量的函数。
type(A), type(B)

(numpy.ndarray, torch.Tensor)